config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to:'home#index'
  get 'home/index'
  post 'charges/update', to: 'charges#update'
  resources:products
  resources :carts
  resources :charges,only: %i(new create)
  resources :order_histories
  # resources :cart_items
  # resources :products, only: %i(show)do
  #   member do
  #     resources :charges, only: %i(new create)
  #   end
  # end

  resources :products,only: %i(show)do
    member do
      resources :cart_items, only: %i(create)
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
  belongs_to :user
  has_many :order_history_items
end

app/models/order_history_item.rb
class OrderHistoryItem < ApplicationRecord
  belongs_to :order_history
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_one :cart   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def new
  end

  def create
    @cart = Cart.find(current_user.id)
    @cart_item = CartItem.new(quantity:params[:product_count],product_id:params[:id],cart_id:@cart.id)
    @cart_item.save!
    redirect_to(carts_path)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = current_user.cart
    @cart_items = CartItem.where(cart_id:@cart.id)
    @sum = 0
    @cart_items.each do |cart_items|
      @sum += cart_items.product.price*cart_items.quantity
    end
  end


end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @cart = current_user.cart
    @cart_items = CartItem.where(cart_id:@cart.id)
    @sum_amount = 0
    @cart_items.each do |cart_items|
      @sum_amount += cart_items.product.price*cart_items.quantity
    end
  end

  def create

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: params[:amount],
      description: 'Rails Stripe customer',
      currency: 'jpy',
    })

    @cart = current_user.cart
    @cart_items = CartItem.where(cart_id:@cart.id)
    @sum_amount = 0
    @cart_items.each do |cart_items|
      @sum_amount += cart_items.product.price*cart_items.quantity
    end

    @order_history = OrderHistory.create!(
      user_id:current_user.id,
      sum:@sum_amount,
      status:"発送待ち"
    )

    @cart_items.each do |cart_item|
      OrderHistoryItem.create!(
        order_history_id:@order_history.id,
        product_id:cart_item.product.id,
        quantity:cart_item.quantity
      )
    end
    @cart_items.destroy_all
    redirect_to "/"

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end

  def update
    @cart = current_user.cart
    @cart_items = CartItem.where(cart_id:@cart.id)
    @item = @cart_items.select{|ci| ci.product_id == params[:produt_id].to_i}.first
    if @item
      @item.quantity = params[:product_count]
      @item.save
    end
  end

  def params_int(model_params)
    return model_params.to_i
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/order_histories_controller.rb
class OrderHistoriesController < ApplicationController
  def index
    @order_histories = OrderHistory.where(user_id:current_user.id)
  end

  def order_history_items_finder(order_history_id)
    return @order_history_items = OrderHistoryItem.where(order_history_id:order_history_id)
  end

  helper_method :order_history_items_finder


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_histories_helper.rb
module OrderHistoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/index.html.erb
<div class="cart_show">
  <div class="cart_content">
    <%=form_tag(new_charge_path,method: :get )do%>
      <h1>My Cart</h1>
        <%if @sum == 0%>
          <h2>カートは空です</h2>
        <%else%>
        <table class="cart_table">
          <%@cart_items.each do |cart_item|%>
            <tr>
              <th>商品名</th>
              <td><%=cart_item.product.name%></td>
            </tr>
            <tr>
              <th>個数</th>
              <td>
                <select data-id=<%=cart_item.product.id%> class="cart_quantity" name="cart_quantity">
                  <%for num in 1..10%>
                    <%if num == cart_item.quantity%>
                      <option selected value=<%=num%>><%=num%></option>
                    <%else%>
                      <option value=<%=num%>><%=num%></option>
                    <%end%>
                  <%end%>
                </select>
              </td>
            </tr>
            <tr>
              <th>小計</th>
              <td><%=cart_item.product.price * cart_item.quantity%></td>
            </tr>
          <%end%>
          <tr>
            <th>合計</th>
            <td id="cart_sum"><%=@sum%></td>
          </tr>
        </table>
        <div class=total_payment>
          <input type="submit"  value="注文する">
        </div>
        <%end%>
    <%end%>
  </div>
</div>
<%= javascript_pack_tag 'cart_sum', 'data-turbolinks-track': 'reload' %>

app/views/order_histories/index.html.erb
<div class="order_histories_index">
  <div class="order_histories_content">
    <h1>注文履歴</h1>
    <h2>注文詳細</h2>
    <%@order_histories.each do |order_history|%>
    <div class="order_histories_container">
      <div class = "order_histories_header">
        <ul>
          <li><span>注文日：</span><%=order_history.created_at%></li>
          <li><span>合計金額：￥</span><%=order_history.sum%></li>
          <li><span>注文状態：</span><%=order_history.status%></li>
        </ul>
      </div>
        <table class ="order_history_items_table">
          <%order_history_items_finder(order_history.id).each do |order_history_item|%>
            <tr>
              <th>商品名</th>
              <td><%=order_history_item.product.name%></td>
            </tr>
            <tr>
              <th>個数</th>
              <td><%=order_history_item.quantity%></td>
            </tr>
          <%end%>
        </table>
     </div>
    <%end%>
  </div>
</div>

app/views/products/index.html.erb
<div class="products_container">
  <table>
    <tr>
      <%@products.each do |product|%>
        <td>
          <%=link_to product_path(product.id), target: "_blank" do%>
            <%=image_tag product.image.url,alt:product,class: "product-img"%><br>
            <%=product.name%>　￥<%=product.price%>
          <%end%>
        </td>
      <%end%>
    </tr>
  </table>
</div>

app/views/products/show.html.erb
<div class="product_show">
    <div class="product_show_container">
      <div class="detail_container" id ="image_container">
        <%=image_tag @product.image.url%>
      </div>
      <div class="detail_container" id ="show_container">
        <h1><%=@product.name%></h1>
        <div class="product_detail">
          <table>
            <tr>
              <th>価格</th>
              <td><%=@product.price%></td>
            </tr>
            <tr>
              <th>商品重量</th>
              <td>399 g</td>
            </tr>
            <tr>
              <th>発送重量</th>
              <td>399 g</td>
            </tr>
            <tr>
              <th>電池</th>
              <td>電池 2 単3形 電池(付属)</td>
            </tr>
            <tr>
              <th>メーカー型番</th>
              <td>3020s-B</td>
            </tr>
            <tr>
              <th>ASIN</th>
              <td>B00ZHYV8QO</td>
            </tr>
            <tr>
              <th>サイズ</th>
              <td>約幅57×奥行48×高さ156mm</td>
            </tr>
          </table>
          <div class="product_payment">
            <div class="payment_container">
              <%=form_tag(cart_items_path) do%>
                <select class="product_count" name="product_count">
                  <%for num in 1..10 do %>
                    <option value=<%=num%>><%=num%></option>
                  <%end%>
                </select>
                <input type="submit" value="カートに入れる">
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>