config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to:'home#index'
  get 'home/index'
  post 'charges/update', to: 'charges#update'
  resources:products
  resources :carts
  resources :charges,only: %i(new create)
  resources :order_histories
  # resources :cart_items
  # resources :products, only: %i(show)do
  #   member do
  #     resources :charges, only: %i(new create)
  #   end
  # end

  resources :products,only: %i(show)do
    member do
      resources :cart_items, only: %i(create)
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
  belongs_to :user
  has_many :order_history_items
end

app/models/order_history_item.rb
class OrderHistoryItem < ApplicationRecord
  belongs_to :order_history
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_one :cart   
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def new
  end

  def create
    @cart = Cart.find(current_user.id)
    @cart_item = CartItem.new(quantity:params[:product_count],product_id:params[:id],cart_id:@cart.id)
    @cart_item.save!
    redirect_to(carts_path)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = current_user.cart
    @cart_items = CartItem.where(cart_id:@cart.id)
    @sum = 0
    @cart_items.each do |cart_items|
      @sum += cart_items.product.price*cart_items.quantity
    end
  end


end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @cart = current_user.cart
    @cart_items = CartItem.where(cart_id:@cart.id)
    @sum_amount = 0
    @cart_items.each do |cart_items|
      @sum_amount += cart_items.product.price*cart_items.quantity
    end
  end

  def create

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: params[:amount],
      description: 'Rails Stripe customer',
      currency: 'jpy',
    })

    @cart = current_user.cart
    @cart_items = CartItem.where(cart_id:@cart.id)
    @sum_amount = 0
    @cart_items.each do |cart_items|
      @sum_amount += cart_items.product.price*cart_items.quantity
    end

    @order_history = OrderHistory.create!(
      user_id:current_user.id,
      sum:@sum_amount,
      status:"発送待ち"
    )

    @cart_items.each do |cart_item|
      OrderHistoryItem.create!(
        order_history_id:@order_history.id,
        product_id:cart_item.product.id,
        quantity:cart_item.quantity
      )
    end
    @cart_items.destroy_all
    redirect_to "/"

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end

  def update
    @cart = current_user.cart
    @cart_items = CartItem.where(cart_id:@cart.id)
    @item = @cart_items.select{|ci| ci.product_id == params[:produt_id].to_i}.first
    if @item
      @item.quantity = params[:product_count]
      @item.save
    end
  end

  def params_int(model_params)
    return model_params.to_i
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_histories_helper.rb
module OrderHistoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="headerInner">
        <div class="header_title">
          <h1><%=link_to"No Cash Mart","/"%></h1>
        </div>
        <div class="global_nav">
          <ul>
            <% if user_signed_in?%>
              <li><%=current_user.email%></li>
              <li>お問い合わせ</li>
              <li><%=link_to"マーケット",products_path%></li>
              <li><%=link_to"カート",carts_path%></li>
              <li><%=link_to"注文履歴",order_histories_path	%></li>
            <%else%>
              <li>お問い合わせ</li>
              <li><%=link_to"マーケット",products_path%></li>
              <li><%=link_to"ログイン",new_user_session_path,class:"login_var"%></li>
              <li><%=link_to"新規登録",new_user_registration_path,class:"login_var"%></li>
            <%end%>

          </ul>
        </div>
      </div>
    </header>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>